language: python
python:
  - "2.6"
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxml2-dev
  - sudo apt-get install -y python-libxml2

install:
  - pip install -r python/requirements.txt
  - pip install coveralls

script:
  - make test_mininet

after_success:
  - coveralls
