language: python
python:
  - "2.6"
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxml2-dev python-libxml2
  - wget ftp://xmlsoft.org/libxml2/python/libxml2-python-2.6.15.tar.gz
  - tar -xzvf libxml2-python-2.6.15.tar.gz
  - cd libxml2-python-2.6.15 && python setup.py install
install:
  - cd ..
  - pip install -r python/requirements.txt
  - pip install coveralls

script:
  - make test_mininet

after_success:
  - coveralls
